apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jhzv69fmu-nodejs 
  janus-idp.io/tekton: jhzv69fmu-nodejs
  backstage.io/kubernetes-id: jhzv69fmu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jhzv69fmu-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml