apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jhzv69fmu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jhzv69fmu-nodejs 
  name: jhzv69fmu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jhzv69fmu-nodejs 
